Update various testing related files.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,98 +66,98 @@ jobs:
     with:
       changed-files: ${{ needs.get-changed-files.outputs.changed-files }}
 
-  build-python-package:
-    name: Python Package
-    if: ${{ inputs.release && success() }}
-    uses: ./.github/workflows/package-action.yml
-    needs:
-      - pre-commit
-    with:
-      version: "${{ inputs.version }}"
-
-  deploy-python-package-test-pypi:
-    name: Deploy Python Package (Test PyPI)
-    uses: ./.github/workflows/deploy-package-action.yml
-    if: ${{ inputs.release && success() }}
-    needs:
-      - pre-commit
-      - test
-      - docs
-      - build-python-package
-    secrets:
-      TEST_PYPI_API_TOKEN: "${{ secrets.TEST_PYPI_API_TOKEN }}"
-    with:
-      version: "${{ inputs.version }}"
-
-  deploy-python-package:
-    name: Deploy Python Package (PyPI)
-    uses: ./.github/workflows/deploy-package-action.yml
-    if: ${{ inputs.release && success() }}
-    needs:
-      - pre-commit
-      - test
-      - docs
-      - build-python-package
-      - deploy-python-package-test-pypi
-    secrets:
-      PYPI_API_TOKEN: "${{ secrets.PYPI_API_TOKEN }}"
-    with:
-      test: false
-      version: "${{ inputs.version }}"
-
-  push-tag:
-    name: Push Version Tag
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-    if: ${{ inputs.release && success() }}
-    needs:
-      - build-python-package
-      - deploy-python-package
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Push Tag
-        uses: rickstaa/action-create-tag@v1
-        with:
-          tag: "v${{ inputs.version }}"
-          message: "Version ${{ inputs.version }}"
-
-  set-pipeline-exit-status:
-    # This step is just so we can make github require this step, to pass checks
-    # on a pull request instead of requiring all
-    name: Set the CI Pipeline Exit Status
-    runs-on: ubuntu-latest
-    if: always()
-    needs:
-      - pre-commit
-      - test
-      - docs
-      - build-python-package
-      - deploy-python-package-test-pypi
-      - deploy-python-package
-      - push-tag
-    steps:
-    - name: Download Exit Status Files
-      if: always()
-      uses: actions/download-artifact@v4.1.7
-      with:
-        name: exitstatus
-        path: exitstatus
-
-    - name: Delete Exit Status Artifacts
-      if: always()
-      uses: geekyeggo/delete-artifact@v2
-      with:
-        name: exitstatus
-        failOnError: false
-
-    - name: Set Pipeline Exit Status
-      run: |
-        tree exitstatus
-        grep -RE 'failure|cancelled' exitstatus/ && exit 1 || exit 0
-
-    - name: Done
-      if: always()
-      run:
-        echo "All workflows finished"
+#  build-python-package:
+#    name: Python Package
+#    if: ${{ inputs.release && success() }}
+#    uses: ./.github/workflows/package-action.yml
+#    needs:
+#      - pre-commit
+#    with:
+#      version: "${{ inputs.version }}"
+#
+#  deploy-python-package-test-pypi:
+#    name: Deploy Python Package (Test PyPI)
+#    uses: ./.github/workflows/deploy-package-action.yml
+#    if: ${{ inputs.release && success() }}
+#    needs:
+#      - pre-commit
+#      - test
+#      - docs
+#      - build-python-package
+#    secrets:
+#      TEST_PYPI_API_TOKEN: "${{ secrets.TEST_PYPI_API_TOKEN }}"
+#    with:
+#      version: "${{ inputs.version }}"
+#
+#  deploy-python-package:
+#    name: Deploy Python Package (PyPI)
+#    uses: ./.github/workflows/deploy-package-action.yml
+#    if: ${{ inputs.release && success() }}
+#    needs:
+#      - pre-commit
+#      - test
+#      - docs
+#      - build-python-package
+#      - deploy-python-package-test-pypi
+#    secrets:
+#      PYPI_API_TOKEN: "${{ secrets.PYPI_API_TOKEN }}"
+#    with:
+#      test: false
+#      version: "${{ inputs.version }}"
+#
+#  push-tag:
+#    name: Push Version Tag
+#    runs-on: ubuntu-latest
+#    permissions:
+#      contents: write
+#    if: ${{ inputs.release && success() }}
+#    needs:
+#      - build-python-package
+#      - deploy-python-package
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#      - name: Push Tag
+#        uses: rickstaa/action-create-tag@v1
+#        with:
+#          tag: "v${{ inputs.version }}"
+#          message: "Version ${{ inputs.version }}"
+#
+#  set-pipeline-exit-status:
+#    # This step is just so we can make github require this step, to pass checks
+#    # on a pull request instead of requiring all
+#    name: Set the CI Pipeline Exit Status
+#    runs-on: ubuntu-latest
+#    if: always()
+#    needs:
+#      - pre-commit
+#      - test
+#      - docs
+##      - build-python-package
+##      - deploy-python-package-test-pypi
+##      - deploy-python-package
+##      - push-tag
+#    steps:
+#    - name: Download Exit Status Files
+#      if: always()
+#      uses: actions/download-artifact@v3
+#      with:
+#        name: exitstatus
+#        path: exitstatus
+#
+#    - name: Delete Exit Status Artifacts
+#      if: always()
+#      uses: geekyeggo/delete-artifact@v2
+#      with:
+#        name: exitstatus
+#        failOnError: false
+#
+#    - name: Set Pipeline Exit Status
+#      run: |
+#        tree exitstatus
+#        grep -RE 'failure|cancelled' exitstatus/ && exit 1 || exit 0
+#
+#    - name: Done
+#      if: always()
+#      run:
+#        echo "All workflows finished"
